Revenue Transactions Dataset

* To analyze revenue transaction patterns by examining sales performance across different outlets, identifying high-performing locations, and evaluating overall business growth.

* To evaluate sales trends over time by analyzing daily, weekly, and monthly transaction data to identify seasonal demand, peak sales periods, and revenue fluctuations.

* To assess customer purchasing behavior by analyzing transaction frequency, item quantities, average transaction value, and payment method preferences to understand customer buying patterns.

* To measure the contribution of key financial metrics by evaluating Net Sales, Tax, and Total Amount to determine their impact on overall revenue generation and profitability.

* To identify operational performance indicators by examining receipt-level transactions, product quantities, and loyalty card usage to uncover opportunities for improving customer retention and sales efficiency.

* To generate data-driven business insights and
recommendations that support strategic decision-making in sales optimization, revenue forecasting, customer engagement, and operational planning through Python-based data analysis and visualization.

Dataset Information

Source: Mendeley Data – Revenue Transactional Dataset

Location: Surabaya, East Java, Indonesia (Data collected from an anonymized Food & Beverage (F&B) MSME operating multiple retail outlets.)

Year/Timeline: January 2025 – September 2025

Domain: Retail Sales & Revenue Analytics (Food & Beverage Industry)

Dataset Size: 53,820 transaction records, 11 transaction features, and 96 product records across 3 retail outlets.

In [1]:
#IMPORTING Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
#DATA LOADED FROM THE LOACL DRIVE
from google.colab import files
uploaded = files.upload()

Saving Transactions.csv to Transactions.csv

In [3]:
#Csv file is converted to datafarme with pandas
df = pd.read_csv("Transactions.csv")

Initial Inspection / Initial EDA

In [4]:
# displaying first 5 rows
df.head()

,Outlet,Date,Time,NetSales,Tax,TotalAmount,ReceiptNumber,Items,TotalItem,PaymentMethod,UseLoyaltyCard
0,SHOP001,02-01-2025,07:01:05,20720.721,2279.279,23000,SHOP001JAN2500001,Basic Latte (Ice Arabica),1,BCA,0
1,SHOP001,02-01-2025,07:04:11,18018.018,1981.982,20000,SHOP001JAN2500002,BLACK (Houseblend),1,BCA,0
2,SHOP002,02-01-2025,07:10:46,39639.640,4360.360,44000,SHOP002JAN2500001,"Friendly Coffee (Hot), Shakencano",2,Cash,0
3,SHOP002,02-01-2025,07:14:25,36036.036,3963.964,40000,SHOP002JAN2500002,"BLACK (Arabica), Americano (Hot Arabica)",2,Cash,0
4,SHOP002,02-01-2025,07:23:05,36036.036,3963.964,40000,SHOP002JAN2500003,"WHITE (Arabica), Susu Oat",2,Cash,0

In [5]:
# To evaluate data health, check for missing values, and monitor memory consumption.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53820 entries, 0 to 53819
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Outlet          53820 non-null  object
 1   Date            53820 non-null  object
 2   Time            53820 non-null  object
 3   NetSales        53820 non-null  float64
 4   Tax             53820 non-null  float64
 5   TotalAmount     53820 non-null  int64
 6   ReceiptNumber   53820 non-null  object
 7   Items           53820 non-null  object
 8   TotalItem       53820 non-null  int64
 9   PaymentMethod   53820 non-null  object
 10  UseLoyaltyCard  53820 non-null  int64
dtypes: float64(2), int64(3), object(6)
memory usage: 4.5+ MB

In [6]:
#to understand the attribute and to check  the column labels
df.columns

Index(['Outlet', 'Date', 'Time', 'NetSales', 'Tax', 'TotalAmount',
       'ReceiptNumber', 'Items', 'TotalItem', 'PaymentMethod',
       'UseLoyaltyCard'],
      dtype='object')

In [7]:
#to understand quick statistical summary of your DataFrame
df.describe()

           NetSales           Tax   TotalAmount     TotalItem  UseLoyaltyCard
count  53820.000000  53820.000000  53820.000000  53820.000000    53820.000000
mean   22016.598672   2421.825705  24438.424378      1.151486        0.032200
std    10172.062610   1118.926902  11290.989512      0.358526        0.176532
min        0.000000      0.000000      0.000000      1.000000        0.000000
25%    18018.018000   1981.982000  20000.000000      1.000000        0.000000
50%    20720.721000   2279.279000  23000.000000      1.000000        0.000000
75%    27027.027000   2972.973000  30000.000000      1.000000        0.000000
max    54054.054000   5945.946000  60000.000000      2.000000        1.000000

In [8]:
df.dtypes

Outlet             object
Date               object
Time               object
NetSales          float64
Tax               float64
TotalAmount         int64
ReceiptNumber      object
Items              object
TotalItem           int64
PaymentMethod      object
UseLoyaltyCard      int64
dtype: object

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.isnull().sum()

Outlet            0
Date              0
Time              0
NetSales          0
Tax               0
TotalAmount       0
ReceiptNumber     0
Items             0
TotalItem         0
PaymentMethod     0
UseLoyaltyCard    0
dtype: int64